export enum AppRoute {
  HOME = "/",
  ADMIN = "/admin",
  ADMIN_MANAGE_USERS = "/admin/manage-users",
  LOGIN = "/login",
  WELCOME_NEW_MEMBER = "/welcome-new-member",
  SEARCH = "/search",
  REEL = "/reel",
  NOTIFICATION = "/notification",
  PROFILE = "/profile",
  SAVED = "/saved",
  USER_SETTINGS = "/user-settings",
  POSTS = "/posts",
  EXPLORE = "/explore",
}
