export enum NotificationType {
  LIKE = "LIKE",
  COMMENT = "COMMENT",
  FOLLOW = "FOLLOW",
  FOLLOW_REQUEST = "FOLLOW_REQUEST",
  FOLLOW_ACCEPTED = "FOLLOW_ACCEPTED",
  MENTION = "MENTION",
  REPLY = "REPLY",
  NEW_USER_JOINED = "NEW_USER_JOINED",
}
