export enum Permission {
  CLEAR_CACHE = "CLEAR_CACHE",
  CHANGE_ACCOUNT_STATUS = "CHANGE_ACCOUNT_STATUS",
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_POSTS = "MANAGE_POSTS",
  VIEW_DASHBOARD = "VIEW_DASHBOARD",

  UPDATE_OWN_PROFILE = "UPDATE_OWN_PROFILE",
}
