export enum QueryKey {
  GET_POSTS = "GET_POSTS",
  GET_POST = "GET_POST",
  GET_USER = "GET_USER",
  GET_USER_SAVEDS = "GET_USER_SAVEDS",
  GET_USER_FOLLOW = "GET_USER_FOLLOW",
  GET_USERS = "GET_USERS",
  GET_POST_COMMENTS = "GET_POST_COMMENTS",
  GET_POST_LIKES = "GET_POST_LIKES",
}

export const QueryStaleTime: Record<QueryKey, number> = {
  [QueryKey.GET_POSTS]: 60000,
  [QueryKey.GET_POST]: 60000,
  [QueryKey.GET_USER]: 180000,
  [QueryKey.GET_POST_COMMENTS]: 60000,
  [QueryKey.GET_POST_LIKES]: 120000,
  [QueryKey.GET_USERS]: 180000,
  [QueryKey.GET_USER_SAVEDS]: 120000,
  [QueryKey.GET_USER_FOLLOW]: 120000,
}
