export enum UnstableCacheKey {
  USER_EMAIL = "USER_EMAIL",
  USER_EXISTS_BY_EMAIL = "USER_EXISTS_BY_EMAIL",
  USER_EXISTS_BY = "USER_EXISTS_BY",
  USER_LIST = "USER_LIST",
  USER_LIST_COUNT = "USER_LIST_COUNT",
  USER_SAVED = "USER_SAVED",
  
  USER_FOLLOW = "USER_FOLLOW",

  POST_LIST = "POST_LIST",
  POST_SINGLE = "POST_SINGLE",
  POST_COMMENT_LIST = "POST_COMMENT_LIST",
  POST_LIKE_LIST = "POST_LIKE_LIST",
  POST_LIKE_EXISTS = "POST_LIKE_EXISTS",
}
