export enum UnstableCacheKey {
  USER_EMAIL = "USER_EMAIL",
  USER_EXISTS_BY_EMAIL = "USER_EXISTS_BY_EMAIL",
  USER_LIST = "USER_LIST",

  POST_LIST = "POST_LIST",
  POST_SINGLE = "POST_SINGLE",
  POST_COMMENT_LIST = "POST_COMMENT_LIST",
}
